// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticsDatabaseLibrary.Context;

namespace StatisticsDatabaseLibrary.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230125090637_PhotoArrayAddedMigration")]
    partial class PhotoArrayAddedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("StatisticsDatabaseLibrary.Entities.CopyBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CopyBooks");
                });

            modelBuilder.Entity("StatisticsDatabaseLibrary.Entities.ScannedPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopyBookId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CopyBookId");

                    b.ToTable("ScannedPhotos");
                });

            modelBuilder.Entity("StatisticsDatabaseLibrary.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StatisticsDatabaseLibrary.Entities.CopyBook", b =>
                {
                    b.HasOne("StatisticsDatabaseLibrary.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StatisticsDatabaseLibrary.Entities.ScannedPhoto", b =>
                {
                    b.HasOne("StatisticsDatabaseLibrary.Entities.CopyBook", "CopyBook")
                        .WithMany("ScannedPhotos")
                        .HasForeignKey("CopyBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
